### PR TITLE
Function to create preference score distribution plot from comparative effectiveness data model

### PR DESCRIPTION
**Pull request by gowthamrao**
Continuing work here https://github.com/OHDSI/SkeletonComparativeEffectStudy/issues/27

### CODE REVIEW

**Comment by schuemie** [comment]
Two things:

1. This function both gets the data for the preference plot, and then plots it. I think it is cleaner if this function just creates the plot, and requires a preferenceScore object as input that the user created using `getPreferenceScoreDistribution`.

2. You're exposing a (rather arbitrary) subset of the styling options of the ggplot object. For most users this will be confusing. Also, advanced users (the only users that will use those options) will be able to override those options once the function has produced the ggplot. Again, to make for a cleaner function, I recommend dropping the options for the user to modify the ggplot theme etc.

**Comment by schuemie** [comment]
Also, I tend to add a `fileName` argument to my plotting functions, so you can directly save it to PNG for example. That saves the user having to figure our the right width and height (and how to save ggplot objects in the first place). See [here](https://github.com/OHDSI/CohortMethod/blob/master/R/PsFunctions.R#L477) for an example.

**Comment by gowthamrao** [comment]
>  I think it is cleaner if this function just creates the plot, and requires a preferenceScore object

You may be right, but: if we are trying to separate data step and plotting step (which i think we should) - the plotting step maybe further generalized. 

```
ggplot2::ggplot(preferenceScore,
                          ggplot2::aes(x = x, y = y, color = group, group = group, fill = group)) +
    ggplot2::geom_density(stat = "identity") + 
    ggplot2::scale_x_continuous(xAxisLabel, limits = c(0, 1)) +
    ggplot2::scale_y_continuous(yAxisLabel)
```

All it needs is an object with a continuous value for x, a continuous value for y, and a grouping variable.

If yes, then we could maintain these in a ohdsi visualization helper package that is part of ohdsi-methods - and use across all OHDSI packages?

is essentially more general - given three values x/y/group.

**Comment by schuemie** [comment]
If you are saying we shouldn't provide plotting functions at all, since that's what ggplot is for, I don't agree. Yes, ideally our data objects are so clear people could easily implement it themselves, but we don't want to require users to understand the data format for each plot. Just adding a simple `plotPreferenceScore` function with some options that internally mostly just calls ggplot will be a great help to people. And it may be the code looks quite similar to another plotting function (but not sure which one?), but from a users's perspective having one function per data type (regardless of the similarities in implementation) would be less confusing.

**Comment by gowthamrao** [comment]
Thanks @schuemie .  i will make changes to this PR

**Comment by schuemie** [comment]
I had made some more comments (about not exposing ggplot options in the function arguments, and adding a filename argument). I don't see them anymore. Could you address those as well?

**Comment by gowthamrao** [comment]
> This function both gets the data for the preference plot, and then plots it. I think it is cleaner if this function just creates the plot, and requires a preferenceScore object as input that the user created using getPreferenceScoreDistribution.

I agree with above, but i am finding it hard to agree with below 

> You're exposing a (rather arbitrary) subset of the styling options of the ggplot object. For most users this will be confusing. Also, advanced users (the only users that will use those options) will be able to override those options once the function has produced the ggplot. Again, to make for a cleaner function, I recommend dropping the options for the user to modify the ggplot theme etc.

- **exposing a (rather arbitrary) subset of the styling options of the ggplot object**  Its not arbitrary.

1.  We are exposing the [entire ggplot2::theme components](https://github.com/OHDSI/SkeletonComparativeEffectStudy/blob/b4fece76cce16406175d6de343e43285afa6462b/R/Plots.R#L110). This is, per my reading of ggplot2, the recommended approach.
2. Color palettes are not part of ggplot2::theme, so ggplot2::scale_* gives that capability. Viridis is the[ default color pallets for ggplot2](https://cran.r-project.org/web/packages/viridis/vignettes/intro-to-viridis.html) and is screen/print/color blind friendly. 

I think this approach makes it simple and easier to maintain.

> Also, I tend to add a fileName argument to my plotting functions, so you can directly save it to PNG for example. That saves the user having to figure our the right width and height (and how to save ggplot objects in the first place).

Agree. This would be useful.

**Comment by gowthamrao** [comment]
> This function both gets the data for the preference plot, and then plots it. I think it is cleaner if this function just creates the plot, and requires a preferenceScore object as input that the user created using getPreferenceScoreDistribution.

I agree with above, but i am finding it hard to agree with below 

> You're exposing a (rather arbitrary) subset of the styling options of the ggplot object. For most users this will be confusing. Also, advanced users (the only users that will use those options) will be able to override those options once the function has produced the ggplot. Again, to make for a cleaner function, I recommend dropping the options for the user to modify the ggplot theme etc.

Agree that an advanced user is able to modify the ggplot object and wont need us to expose these styling options. But i am not convinced that other users will be confused. They dont have to use them and defaults are assigned to these options, Plus, i think we should try to leverage the palette and themes options in ggplot2 - that makes creating plots easier to maintain.  I would recommend we retain these.

> Also, I tend to add a fileName argument to my plotting functions, so you can directly save it to PNG for example. That saves the user having to figure our the right width and height (and how to save ggplot objects in the first place).

Agree. This would be useful.

**Comment by schuemie** [comment]
> Agree that an advanced user is able to modify the ggplot object and wont need us to expose these styling options. But i am not convinced that other users will be confused. They dont have to use them and defaults are assigned to these options, Plus, i think we should try to leverage the palette and themes options in ggplot2 - that makes creating plots easier to maintain. I would recommend we retain these.

I don't disagree with the use of palettes, but I still disagree with exposing these ggplot attributes. The main reason is that they're an arbitrary selection of things a user might want to change, and advanced users can already change them outside of the function. To illustrate this point, consider that under your logic, function that produces a vector of numbers should also have `mean`, `median`, etc. arguments, because those are things people could apply to the vector afterwards, so they should be  in the function.

Also remember that we're trying to present a consistent interface to the users of our packages. If we decide to expose the ggplot theme in this function, we will have to do it in every one of our plotting functions in the Methods Library. And all that while the theme can easily be modified afterwards, outside of the function.

**Comment by gowthamrao** [comment]
@schuemie  the plots have been changed per discussion

**Review by schuemie — APPROVED** [review]

**Pull request merged**
